
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: ${GCP_PROJECT_ID}
      auth:
        workloadIdentity:
          clusterLocation: ${GCP_REGION}
          clusterName: ${PROJECT_NAME}-container-cluster
          clusterProjectID: ${GCP_PROJECT_ID}
          serviceAccountRef:
            name: custom-service-account
            namespace: default
            