
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: deploy-external-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: django-config
    creationPolicy: Owner
  data:
  - secretKey: DJANGO_SECRET
    remoteRef:
      key: DJANGO_SECRET
  - secretKey: REDIS_HOST_IP
    remoteRef:
      key: REDIS_HOST_IP
  - secretKey: DATABASE_NAME
    remoteRef:
      key: DATABASE_NAME
  - secretKey: DATABASE_USER_NAME
    remoteRef:
      key: DATABASE_USER_NAME
  - secretKey: DATABASE_USER_PASSWORD
    remoteRef:
      key: DATABASE_USER_PASSWORD
  - secretKey: RESERVED_IP
    remoteRef:
      key: RESERVED_IP
  - secretKey: STATIC_BUCKET_NAME
    remoteRef:
      key: STATIC_BUCKET_NAME
  - secretKey: MEDIA_BUCKET_NAME
    remoteRef:
      key: MEDIA_BUCKET_NAME